### ISSUE TITLE
sql错了

### ISSUE THREAD

**Issue by PhoenixZeng** [ScorpionTeam/mall#1]

**Comment by PhoenixZeng** [comment]
-- -----------------------------------------------------
-- Table `mall`.`t_good_attr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mall`.`t_good_attr` (
  `id` BIGINT(20) NOT NULL,
  `goodId` BIGINT(20) NULL,
  `` VARCHAR(45) NULL COMMENT '规格名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

**Comment by PhoenixZeng** [comment]
还有几张空表

**Comment by Jarvens** [comment]
没太注意。表确实不完善。

**Comment by hsy16007** [comment]
我也拜读了一下，表结构差别很大；
可否提供下sql，谢谢，Email:  hsy16007@163.com
